// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ike_nVImMcIcEl92YwZn3QJY53sUtDk',
    appId: '1:787297264937:web:c243fe177ddcb8f7db4338',
    messagingSenderId: '787297264937',
    projectId: 'crudtutorial-77371',
    authDomain: 'crudtutorial-77371.firebaseapp.com',
    storageBucket: 'crudtutorial-77371.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAp1nD0Sse9w-BZJ5634dpoFbU4WdNHd0',
    appId: '1:787297264937:android:d9a955ff7276af9fdb4338',
    messagingSenderId: '787297264937',
    projectId: 'crudtutorial-77371',
    storageBucket: 'crudtutorial-77371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfWUKUEhFu2Bi3pbPPOh3Ct6XhjnK3Td8',
    appId: '1:787297264937:ios:749b0bf8139b5514db4338',
    messagingSenderId: '787297264937',
    projectId: 'crudtutorial-77371',
    storageBucket: 'crudtutorial-77371.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfWUKUEhFu2Bi3pbPPOh3Ct6XhjnK3Td8',
    appId: '1:787297264937:ios:28e4080234071dacdb4338',
    messagingSenderId: '787297264937',
    projectId: 'crudtutorial-77371',
    storageBucket: 'crudtutorial-77371.appspot.com',
    iosBundleId: 'com.example.todoFirebase.RunnerTests',
  );
}
